### ISSUE TITLE
Tags not being created/pushed when releasing

### ISSUE THREAD

**Issue by jessepinho** [groupon/nlm#37]
I have a slightly unusual situation: I'm using nlm for an app, not a library. I don't use CI for the app, so I run `nlm release --commit` as part of the [deploy script](https://github.com/jessepinho/trumpymctweetface.com/blob/master/package.json#L12).

When I run this, it successfully creates a release in GitHub and a commit with the version number. However, *it doesn't create a Git tag with `vX.X.X`*. I've checked both on my machine and on GitHub, and the tag wasn't created in either place.

As a result, on my *next* deploy, NLM fails, because it can't find a git tag with the version number currently in package.json.

Note that I haven't configured CI at all, since I'm not using it. I'm not sure if this is relevant to the problem, though.

Any ideas?

**Comment by jkrems** [comment]
> When I run this, it successfully creates a release in GitHub

Maybe I'm missing something but that should be impossible. Github releases *should* imply a tag because that's how we create the tag: https://github.com/groupon/nlm/blob/946458d3a9796a545361bfb12bf4753e5c370654/lib/steps/github-release.js#L47

The releases page actually collapses tags & releases into one list:
* All releases of nlm: https://github.com/groupon/nlm/releases
* Click on one and the URL says `/tag/...`: https://github.com/groupon/nlm/releases/tag/v3.2.0
* And that is the tag: https://github.com/groupon/nlm/tree/v3.2.0

Side note: `nlm` definitely is meant to be triggered from CI. If you want to use it for app, that's absolutely supported! Just add `"private": true` to your `package.json` and everything should just work. [`"private": true` is how you mark a project as "please don't publish to npm"](https://docs.npmjs.com/files/package.json#private) and `nlm` will respect that setting.

**Comment by jessepinho** [comment]
@jkrems Hmm... I did indeed forget the `GH_TOKEN` variable, but it was able to create commits/releases in the past even without that.

So I just added it, and it didn't change anything.

> Github releases should imply a tag because that's how we create the tag

I was looking at that code as well and it makes no sense to me either. But I just created [a new release](https://github.com/jessepinho/trumpymctweetface.com/commit/2e8fc641a7988c97ddd3c9df214e922e04a2d07a) (committed by nlm), and yet it doesn't show up in [releases](https://github.com/jessepinho/trumpymctweetface.com/releases) or [tags](https://github.com/jessepinho/trumpymctweetface.com/tags).

**Comment by jkrems** [comment]
Ah, sorry. By "creating a release" I thought you meant a Github release, not just a changelog entry. It will create that version commit using your normal git credentials (it's a boring old `git commit`). But it shouldn't push the commit or create the release if it doesn't have the `GH_TOKEN` and is in the proper release mode. `DEBUG=nlm*` should tell you if and why it's skipping things.

**Comment by jessepinho** [comment]
Heyyy [it worked](https://github.com/jessepinho/trumpymctweetface.com/releases)! I'm, uh, not exactly sure what I changed, unfortunately. I think it had to do with not having the `GH_TOKEN` set properly in the environment. Anyway, thanks for your help :)
